### ISSUE TITLE
spaceBetweenWord bug

### ISSUE THREAD

**Issue by srtager555** [Carlos-And-Ponce/wrapping-letters#2]
Does not detect the first word on the sentence when the attribute `spaceBetweenWord` is `true`.

**Comment by Carlos-And-Ponce** [comment]
With the new code structure, this problem is solved.

**Comment by srtager555** [comment]
With the new code structure, this problem is fixed. Commit 6b2f2ac412c0def657f90768a1171d1bfb1f4e4a
